**#Importando Bibliotecas**

In [1]:
import pandas as pd

**# Lendo dados do Projeto e transformando em um DataFrame do Pandas**

In [2]:
dataFrame = pd.read_csv(r"..\data\PNADC - Projeto.csv")
dataFrame

       UF  Sexo  Idade  Cor  Anos de Estudo  Renda    Altura
0      11     0     23    8              12    800  1.603808
1      11     1     23    2              12   1150  1.739790
2      11     1     35    8              15    880  1.760444
3      11     0     46    2               6   3500  1.783158
4      11     1     47    8               9    150  1.690631
...    ..   ...    ...  ...             ...    ...       ...
76835  53     1     46    2              11    812  1.687030
76836  53     0     30    4               7   1500  1.792934
76837  53     0     32    8              12   1300  1.830587
76838  53     0     57    8               4   1500  1.726344
76839  53     0     38    8               4    900  1.658305

[76840 rows x 7 columns]

**#Identificando Tipos de Dados do DataSet**

In [26]:
dataFrame["UF"].unique()
#Qualitativa Nominal

array([11, 12, 13, 14, 15, 16, 17, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31,
       32, 33, 35, 41, 42, 43, 50, 51, 52, 53])

In [3]:
dataFrame["Sexo"].unique()
#Qualitativa Nominal

array([0, 1])

In [28]:
dataFrame["Idade"].unique()
#Quantitativa discreta

array([23, 35, 46, 47, 34, 57, 60, 50, 26, 49, 52, 38, 45, 43, 53, 62, 69,
       41, 25, 33, 44, 65, 32, 30, 64, 31, 63, 40, 28, 37, 39, 36, 73, 56,
       27, 42, 51, 29, 24, 55, 67, 66, 61, 54, 48, 80, 79, 71, 59, 19, 22,
       77, 58, 17, 72, 70, 18, 21, 20, 68, 74, 76, 75, 84, 85, 78, 15, 82,
       95, 13, 83, 81, 87, 88, 16, 91, 92, 97, 89, 90, 86, 94, 14, 99])

In [29]:
dataFrame["Cor"].unique()
#Qualitativa Nominal

array([8, 2, 4, 6, 0])

In [30]:
dataFrame["Anos de Estudo"].unique()
#Qualitativa Ordinal

array([12, 15,  6,  9, 14, 16, 10,  1,  5,  7,  3,  2,  4,  8, 11, 17, 13])

In [31]:
dataFrame["Renda"].unique()
#Quantitativa Contínua

array([  800,  1150,   880, ..., 36000,  1329,  5260], shape=(1606,))

In [32]:
dataFrame["Altura"].unique()
#Quantitativa Contínua

array([1.60380762, 1.73978983, 1.76044382, ..., 1.83058738, 1.72634426,
       1.65830485], shape=(76831,))

**#análise descritiva das variáveis qualitativas**

#calculando frequências

In [4]:
frenquecia_sexos = dataFrame.Sexo.value_counts()
frequencia_relativa_sexos = dataFrame.Sexo.value_counts(normalize=True)

In [7]:
sexos = pd.DataFrame(
    {
        "Frequência": frenquecia_sexos,
        "Percentual (%)": frequencia_relativa_sexos * 100
    }
)
sexos

      Frequência  Percentual (%)
Sexo
0          53250       69.299844
1          23590       30.700156

#dando nome às linhas

In [8]:
capa_sexos = {
    0: "Masculino",
    1: "Feminimo"
}

sexos.rename(index=capa_sexos, inplace=True)

sexos

           Frequência  Percentual (%)
Sexo
Masculino       53250       69.299844
Feminimo        23590       30.700156

#criando uma tabela que mostra o cruzamento entre as váriáveis Sexo e Cores (frequência)

In [11]:
capa_cores = {
    0: "Indígena",
    2: "Branca",
    4: "Preta",
    6: "Amarela",
    8: "Parda",
    9: "Sem declaração"
}

sexos_e_cores = pd.crosstab(dataFrame.Sexo, dataFrame.Cor)
sexos_e_cores.rename(index=capa_sexos, columns=capa_cores, inplace=True)
sexos_e_cores

Cor        Indígena  Branca  Preta  Amarela  Parda
Sexo
Masculino       256   22194   5502      235  25063
Feminimo        101    9621   2889      117  10862

In [14]:
sexos_e_cores_percentuais = pd.crosstab(dataFrame.Sexo, dataFrame.Cor, normalize=True) * 100
sexos_e_cores_percentuais.rename(index=capa_sexos, columns=capa_cores, inplace=True)
sexos_e_cores_percentuais

Cor        Indígena     Branca     Preta   Amarela      Parda
Sexo
Masculino  0.333160  28.883394  7.160333  0.305830  32.617126
Feminimo   0.131442  12.520822  3.759761  0.152264  14.135867

#criando uma tabela que mostra o cruzamento entre as váriáveis Sexo e Cores e faz uma média da renda

In [16]:
sexos_e_cores_renda = pd.crosstab(dataFrame.Sexo, dataFrame.Cor, aggfunc='mean', values=dataFrame.Renda)
sexos_e_cores_renda.rename(index=capa_sexos, columns=capa_cores, inplace=True)
sexos_e_cores_renda

Cor           Indígena       Branca        Preta      Amarela        Parda
Sexo
Masculino  1081.710938  2925.744435  1603.861687  4758.251064  1659.577425
Feminimo   2464.386139  2109.866750  1134.596400  3027.341880  1176.758516

**#análise descritiva das variáveis quantitativas**

#criando segmentações de renda

In [19]:
agrupamento = [
    0, 1576, 3152, 7880, 15760, 200000
]

rotulos = [
    'E', 'D', 'C', 'B', 'A'
]

dataFrame_classificado_pela_renda = pd.cut(
    x=dataFrame.Renda,
    bins=agrupamento,
    labels=rotulos,
    include_lowest=True
)

dataFrame_classificado_pela_renda

0        E
1        E
2        E
3        C
4        E
        ..
76835    E
76836    E
76837    E
76838    E
76839    E
Name: Renda, Length: 76840, dtype: category
Categories (5, object): ['E' < 'D' < 'C' < 'B' < 'A']

#frequencia de cada renda

In [20]:
frequencia_renda = pd.value_counts(
    pd.cut(
        x=dataFrame.Renda,
        bins=agrupamento,
        labels=rotulos,
        include_lowest=True
    )
)

frequencia_relativa_renda = pd.value_counts(
    pd.cut(
        x=dataFrame.Renda,
        bins=agrupamento,
        labels=rotulos,
        include_lowest=True
    ),
    normalize=True
)

df_frequencia_renda = pd.DataFrame(
    {
        "Frequencia": frequencia_renda,
        "Percentual (%)": frequencia_relativa_renda
    }
)

df_frequencia_renda

C:\Users\mathe\AppData\Local\Temp\ipykernel_46940\773389496.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  frequencia_renda = pd.value_counts(
C:\Users\mathe\AppData\Local\Temp\ipykernel_46940\773389496.py:10: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  frequencia_relativa_renda = pd.value_counts(

       Frequencia  Percentual (%)
Renda
E           49755        0.647514
D           16700        0.217335
C            7599        0.098894
B            2178        0.028345
A             608        0.007913